"""沙盒服务 API — 允许用户将当前终端进程加入独占设备的 cgroup 沙盒。

内网用户可通过 HTTP 或 neu-sbox 客户端调用：
  POST /sandbox/acquire   → 创建沙盒，把调用者的 shell PID 加入
  POST /sandbox/join      → 把 host PID 加入沙盒
  POST /sandbox/release   → 销毁沙盒，释放设备
  GET  /sandbox/list      → 列出自己的沙盒

容器不走"搬进程": 容器留在 docker 自己的 cgroup 里，由节点级 OCI runtime
hook 在容器 ENTRYPOINT 之前登记 mount namespace（见 ``docs/container-registration.md``），
借到它所在沙盒的设备授权，容器退出时由 Worker 的 pidfd 监听注销。
容器归属登记不在这里 —— 本模块不提供容器登记端点。
"""

import logging
import pwd
from concurrent.futures import TimeoutError as FutureTimeout

from flask import Blueprint, request

from neu_box.runtime import devices
from neu_box.runtime.containers import DockerExecutorError
from neu_box.runtime.sandbox import (
    SandboxAllocationPaused,
    SbxManager,
)
from neu_box.scheduling.queue import TaskQueue
from neu_box.scheduling.sessions import AcquireFailure
from neu_box.storage import Database

logger = logging.getLogger(__name__)
sandbox_bp = Blueprint('sandbox', __name__)



def _normalize_device_ids(raw: list, all_devices: list[str]) -> list[str] | None:
    """将用户指定的设备 ID 归一化为 ["major:minor", ...] 格式。

    支持两种输入：
      - 纯数字: ["1","3"] → 在所有设备中按 minor 匹配实际 major:minor
      - major:minor: 与本机设备节点完全一致时原样返回
    """
    available = set(all_devices)
    result = []
    for d in raw:
        d = str(d).strip()
        if not d:
            continue
        if ':' in d:
            if d not in available:
                return None
            device = d
        else:
            # 纯数字 → 在所有设备中匹配 minor 号
            device = None
            for dev in all_devices:
                if dev.endswith(f':{d}'):
                    device = dev
                    break
            if device is None:
                return None
        if device not in result:
            result.append(device)
    return result if result else None


def _find_sandbox_for_pid(pid: int) -> str | None:
    """通过 /proc/<pid>/cgroup 查找 PID 所在的沙盒名称。"""
    try:
        with open(f'/proc/{pid}/cgroup') as f:
            for line in f:
                # cgroup v2 格式: "0::/sandbox_sbx_pengyt_12345.slice"
                if 'sandbox_' in line:
                    leaf = line.strip().rsplit('/', 1)[-1]
                    return (
                        leaf[len('sandbox_'):]
                        if leaf.startswith('sandbox_') else leaf
                    )
    except Exception:
        pass
    return None


def _sandbox_owner(name: str) -> str:
    """Extract the owner from a generated ``sbx_<owner>_<id>.slice`` name.

    System usernames may contain underscores.  The allocation ID generated by
    Worker is the final component, so split from the right rather than
    treating the second underscore as the owner boundary.
    """
    if not name.startswith('sbx_'):
        return ''
    stem = name[:-6] if name.endswith('.slice') else name
    payload = stem[4:]
    owner, separator, _identifier = payload.rpartition('_')
    return owner if separator else ''


def _verify_pid_owner(pid: int, username: str) -> bool:
    """校验 PID 是否属于 username。root 进程（如 Docker 容器）直接放行。"""
    try:
        with open(f'/proc/{pid}/status') as f:
            for line in f:
                if line.startswith('Uid:'):
                    real_uid = int(line.split()[1])
                    if real_uid == 0:          # root → Docker 容器等，放行
                        return True
                    pw = pwd.getpwnam(username)
                    return real_uid == pw.pw_uid
    except Exception:
        pass
    return False


def _docker_error_status(exc: DockerExecutorError) -> int:
    if exc.code == 'docker_container_not_found':
        return 404
    if exc.code in {'docker_unavailable', 'docker_sdk_unavailable'}:
        return 503
    if exc.code in {
        'docker_container_changed',
        'docker_container_not_running',
        'docker_container_registered_elsewhere',
        'docker_container_already_registered',
        'sandbox_not_active',
    }:
        return 409
    if exc.code in {'docker_container_state_failed'}:
        return 503
    if exc.code in {
        'sandbox_container_bind_failed',
        'sandbox_container_unbind_failed',
    }:
        return 500
    return 400


def _docker_error_response(exc: DockerExecutorError):
    return {'error': str(exc), 'code': exc.code}, _docker_error_status(exc)


def _worker_paused_response():
    return {
        'error': 'Worker 处于暂停维护状态，暂不创建新沙盒',
        'code': 'worker_paused',
    }, 503


@sandbox_bp.route('/acquire', methods=['POST'])
def acquire():
    """创建沙盒并加入指定 PID（宿主机进程）。

    请求体:
        { "username": "pengyt", "pid": 12345, "device_num": 1,
          "cpu": 0, "memory": 0, "mem_unit": "GB" }

    容器不在这里创建沙盒: 容器由沙盒里的 shell 起（submit 或 neu-sbox
    docker run），启动时由 OCI runtime hook 自动登记归属，借它所在沙盒的
    授权。

    响应中的 devices 使用本机实际发现的 major:minor。
    """
    body = request.get_json(silent=True) or {}

    username = (body.get('username') or '').strip()
    requested_pid = body.get('pid', 0)
    device_num = body.get('device_num', 0)
    device_ids = body.get('device_ids')  # 可选: minor 号或本机实际 major:minor
    cpu = body.get('cpu', 0)
    mem_val = body.get('memory', 0)
    mem_unit = body.get('mem_unit', 'GB')
    priority = body.get('priority', 0)

    if not username or not requested_pid:
        return {'error': 'username 和 pid 为必填参数'}, 400
    if not isinstance(requested_pid, int) or requested_pid <= 0:
        return {'error': 'pid 必须为正整数'}, 400
    if not isinstance(device_num, int) or device_num < 0:
        return {'error': 'device_num 必须是非负整数'}, 400
    if not isinstance(cpu, int) or cpu < 0:
        return {'error': 'cpu 必须是非负整数'}, 400
    # 和命令任务同一套语义：0=普通，1=赶论文。越界由数据层拒（task）或这里拒
    # （acquire）—— acquire 不落库，所以校验落在这一层。
    if not isinstance(priority, int) or isinstance(priority, bool) \
            or not 0 <= priority <= 1:
        return {'error': f'priority 只能是 0（普通）或 1（赶论文）: {priority!r}'}, 400
    if not isinstance(mem_val, int) or mem_val < 0:
        return {'error': 'memory 必须是非负整数'}, 400
    mem_unit = str(mem_unit).upper()
    if mem_unit not in {'GB', 'MB'}:
        return {'error': 'mem_unit 必须是 GB 或 MB'}, 400

    pid = requested_pid
    if not _verify_pid_owner(pid, username):
        return {
            'error': f'PID {pid} 不属于用户 {username}，或进程不存在'
        }, 403

    # 同一 PID 不能隐式替换 sandbox；release 和 acquire 必须是两个操作。
    sbx = SbxManager.get_instance()
    if getattr(sbx, 'allocations_paused', lambda: False)():
        return _worker_paused_response()

    old_name = _find_sandbox_for_pid(pid)
    if old_name:
        return {
            'error': f'PID {pid} 已在沙盒 {old_name} 中；请先 release',
            'sandbox_name': old_name,
        }, 409

    def validate_request_pid():
        if not _verify_pid_owner(pid, username):
            raise AcquireFailure(
                f'PID {pid} 已不属于用户 {username} 或已退出',
                'pid_owner_changed',
            )
        if _find_sandbox_for_pid(pid):
            raise AcquireFailure(
                f'PID {pid} 已加入其他沙盒', 'pid_already_sandboxed',
            )

    # 转换内存格式
    if mem_val == 0:
        sandbox_mem = '0'
    elif mem_unit == 'GB':
        sandbox_mem = f'{mem_val}G'
    else:
        sandbox_mem = f'{mem_val}M'

    # 归一化 device_ids → ["major:minor", ...]
    all_devices = devices.discover_nodes()
    if not device_ids and device_num > len(all_devices):
        return {'error': f'设备不足: 需要 {device_num} 个, 系统共 {len(all_devices)} 个'}, 400
    normalized_ids = None
    if device_ids is not None and not isinstance(device_ids, list):
        return {'error': 'device_ids 必须是数组'}, 400
    if device_ids:
        normalized_ids = _normalize_device_ids(device_ids, all_devices)
        if normalized_ids is None:
            return {'error': f'device_ids 包含不存在的设备: {device_ids}'}, 400

    # acquire 与命令任务共用 TaskQueue；设备不足时保持排队，不直接绕过调度器。
    try:
        queue = TaskQueue.get_instance()
        pending = queue.enqueue_acquire(
            owner=username,
            pid=pid,
            cpu=cpu,
            mem=sandbox_mem,
            device_num=device_num if not normalized_ids else 0,
            device_ids=normalized_ids,
            device_root=None,
            priority=priority,
            validator=(
                validate_request_pid
            ),
        )
        try:
            result = pending.result.result(timeout=0.2)
            queue.acquire_result(pending.request_id, consume=True)
        except FutureTimeout:
            return {
                'acquire_id': pending.request_id,
                'status': 'queued',
                'message': '资源暂不可用，申请已进入调度队列',
            }, 202
        except Exception:
            queue.acquire_result(pending.request_id, consume=True)
            raise
    except SandboxAllocationPaused:
        return _worker_paused_response()
    except DockerExecutorError as exc:
        return _docker_error_response(exc)
    except AcquireFailure as exc:
        if exc.code.startswith('docker_'):
            return _docker_error_response(
                DockerExecutorError(str(exc), exc.code),
            )
        status = 409 if exc.code in {'pid_owner_changed', 'pid_already_sandboxed'} else 503
        return {'error': str(exc), 'code': exc.code}, status

    sandbox_name = result['sandbox_name']
    allocated_devices = result['devices']
    logger.warning(
        "用户 %s PID %s 已加入沙盒 '%s'，独占设备 %s",
        username, pid, sandbox_name, allocated_devices,
    )

    return {
        'sandbox_name': sandbox_name,
        'devices': allocated_devices,
        'message': f'PID {pid} 已加入沙盒 {sandbox_name}，独占设备 {allocated_devices}',
    }, 201


@sandbox_bp.route('/acquire/<request_id>', methods=['GET'])
def acquire_status(request_id: str):
    """查询排队中的 acquire；完成后消费一次结果。"""
    queue = TaskQueue.get_instance()
    state = queue.acquire_result(request_id)
    if state is None:
        return {'error': 'acquire 请求不存在'}, 404
    if state['status'] == 'queued':
        return state, 202
    if state['status'] == 'failed':
        queue.acquire_result(request_id, consume=True)
        code = state.get('code', 'sandbox_acquire_failed')
        if code.startswith('docker_'):
            return _docker_error_response(DockerExecutorError(state['error'], code))
        return state, 409
    queue.acquire_result(request_id, consume=True)
    return state['result'], 201


@sandbox_bp.route('/release', methods=['POST'])
def release():
    """释放沙盒: 还一个，收其余。

    请求体: { "sandbox_name": "sbx_pengyt_12345.slice" }

    "还一个、收其余" 指：归还 acquire 借出去的那个终端（join 时记了
    origin），收掉沙盒里长出来的进程，停掉挂靠的容器（撤登记 →
    ``docker stop`` → 等它真的退出 → 放 pin；**只停不删**，可写层留给用户，
    理由见 ``docs/isolation.md``）。是否涉及容器在内部判断，客户端只需要报
    沙盒名。
    """
    body = request.get_json(silent=True) or {}
    sandbox_name = (body.get('sandbox_name') or '').strip()

    if not sandbox_name:
        return {'error': 'sandbox_name 为必填参数'}, 400

    sbx = SbxManager.get_instance()

    # 调用方可以报自己的 host PID：销毁的最后一步是 cgroup.kill，而调用方可能
    # 就住在沙盒 cgroup 里 —— `neubox release` 是被借的 shell fork 出来的子
    # 进程，cgroup 成员身份随 fork 继承，不先搬出去就会被自己这次销毁带走
    # （用户看到 `zsh: killed`、退出码 137）。搬不动不算错误：调用方不在沙盒
    # 里时本来就无事可做。
    host_pid = body.get('host_pid')
    if host_pid is not None:
        try:
            caller_pid = int(host_pid)
        except (TypeError, ValueError):
            return {'error': 'host_pid 必须是整数'}, 400
        sbx.evacuate_caller(sandbox_name, caller_pid)

    # acquire 属于 TaskQueue 的长期 running 生命周期。通过队列释放可确保
    # pause/maintenance 在 destroy 完成前仍能看到该 sandbox；命令任务或
    # 历史遗留 sandbox 则保留直接 destroy 的兼容路径。
    queue = None
    try:
        # Worker 正常运行时队列单例已由 app 启动；release 的兼容路径不应
        # 为一个历史 sandbox 在维护/单元测试环境中强行初始化数据库队列。
        queue = TaskQueue._instance
        is_running_acquire = (
            queue is not None and queue.has_running_acquire(sandbox_name)
        )
    except Exception:
        # 维护/迁移期间队列数据库可能暂不可用；直接 destroy 保持旧版
        # release 的可用性，native manager 仍会按其持久化状态清理。
        logger.exception('读取 acquire 生命周期失败，回退直接销毁')
        is_running_acquire = False

    try:
        if is_running_acquire:
            ok = queue.release_acquire(sandbox_name)
        else:
            ok = sbx.destroy_sandbox(sandbox_name)
    except DockerExecutorError as exc:
        return _docker_error_response(exc)
    if ok:
        logger.warning("沙盒 '%s' 已手动释放", sandbox_name)
        return {'message': f'沙盒 {sandbox_name} 已销毁', 'sandbox_name': sandbox_name}, 200
    else:
        return {
            'error': f'沙盒 {sandbox_name} 销毁失败',
            'sandbox_name': sandbox_name,
        }, 500


def _check_sandbox_owner(sandbox_name: str, username: str):
    """沙盒名的 owner 段必须与调用者一致；返回错误响应，或 None。"""
    if not sandbox_name.startswith('sbx_'):
        return {'error': '不支持的沙盒名称格式'}, 400
    owner = _sandbox_owner(sandbox_name)
    if owner != username:
        return {
            'error': f'沙盒 "{sandbox_name}" 不属于用户 {username}（属于 {owner}）'
        }, 403
    return None


@sandbox_bp.route('/join', methods=['POST'])
def join():
    """将指定 PID 加入已有沙盒。

    请求体:
        { "username": "pengyt", "pid": 12345,
          "sandbox_name": "sbx_pengyt_67890.slice" }

    校验:
      1. PID 必须属于 username（通过 /proc/<pid>/status 的 UID 校验）
      2. 沙盒名的 owner 段必须与 username 一致
    """
    body = request.get_json(silent=True) or {}
    username = (body.get('username') or '').strip()
    pid = body.get('pid', 0)
    sandbox_name = (body.get('sandbox_name') or '').strip()

    if not username or not pid:
        return {'error': 'username 和 pid 为必填参数'}, 400
    if not isinstance(pid, int) or isinstance(pid, bool) or pid <= 0:
        return {'error': 'pid 必须为正整数'}, 400
    if not sandbox_name:
        return {'error': 'sandbox_name 为必填参数'}, 400
    if not _verify_pid_owner(pid, username):
        return {
            'error': f'PID {pid} 不属于用户 {username}，或进程不存在'
        }, 403

    error = _check_sandbox_owner(sandbox_name, username)
    if error is not None:
        return error

    # 直接把 PID 写入目标 cgroup。cgroup v2 会原子地从旧 cgroup 移动
    # 进程；先写 root 再 join 会在目标校验/写入失败时意外丢失原有隔离。
    sbx = SbxManager.get_instance()
    if not sbx.join_sandbox(sandbox_name, pid):
        return {'error': '加入沙盒失败'}, 500

    logger.warning("用户 %s 将 PID %s 加入沙盒 '%s'", username, pid, sandbox_name)
    return {
        'sandbox_name': sandbox_name,
        'pid': pid,
        'message': f'PID {pid} 已加入沙盒 {sandbox_name}',
    }, 200


@sandbox_bp.route('/status', methods=['GET'])
def sandbox_status():
    """查这个进程在哪个沙盒里。

    Query:
      ?pid=12345        宿主机 PID —— 沙盒里的 shell 报自己的 $$ 就行
      ?container=name   已登记容器的 Docker name/ID（私有 PID namespace）

    响应: { "sandbox_name": "sbx_..." | null, "sandbox": {...} | null }
    """
    container_ref = (request.args.get('container') or '').strip()
    caller_pid = request.args.get('pid')
    if container_ref:
        name = None
        for row in Database.get_instance().list_containers():
            if container_ref in {
                    str(row.get('container_ref') or ''),
                    str(row.get('container_id') or ''),
            }:
                name = row.get('sandbox_name')
                break
        if not name:
            return {'sandbox_name': None, 'sandbox': None}, 200
    elif caller_pid is None:
        return {'error': 'pid 为必填参数'}, 400
    else:
        try:
            pid = int(caller_pid)
        except (TypeError, ValueError):
            return {'error': 'pid 必须为正整数'}, 400
        if pid <= 0:
            return {'error': 'pid 必须为正整数'}, 400

        name = _find_sandbox_for_pid(pid)
        if not name:
            return {'sandbox_name': None, 'sandbox': None}, 200

    record = Database.get_instance().get_sandbox(name)
    sandbox = None
    if record:
        sandbox = {
            'name': name,
            'owner': _sandbox_owner(name),
            'cpu': record.get('cpu', 0),
            'mem': record.get('mem', '0'),
            'devices': record.get('devices', []),
            'created_at': record.get('created_at'),
            'state': record.get('state'),
            'device_paths': devices.node_paths(),
        }
    return {'sandbox_name': name, 'sandbox': sandbox}, 200


@sandbox_bp.route('/list', methods=['GET'])
def list_sandboxes():
    """列出沙盒及其资源信息。

    Query:
      ?username=pengyt                         按用户过滤

    响应: { sandboxes: [...] }
    """
    username = (request.args.get('username') or '').strip()
    sandboxes = []
    for record in Database.get_instance().list_sandboxes():
        name = record.get('name') or ''
        if username and not name.startswith(f"sbx_{username}_"):
            continue
        sandboxes.append({
            'name': name,
            'owner': _sandbox_owner(name),
            'cpu': record.get('cpu', 0),
            'mem': record.get('mem', '0'),
            'devices': record.get('devices', []),
            'created_at': record.get('created_at'),
            'pids': record.get('pids', []),
            'state': record['state'],
        })
    return {'sandboxes': sandboxes}, 200
